import { Noto_Serif, Noto_Serif_Devanagari } from "next/font/google";
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { ConfigProvider } from "antd";

const notoSerifDevnagari = Noto_Serif_Devanagari({
  variable: "--font-noto-serif-devnagari",
  subsets: ["latin"],
  weight: ['300', '400', '500', '600', '700'],
  preload: true,
  display: "swap",
});

const notoSerif = Noto_Serif({
  variable: "--font-noto-serif",
  subsets: ["latin"],
  weight: ['300', '400', '500', '600', '700'],
  preload: true,
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${notoSerifDevnagari.className} antialiased`}>
        <AntdRegistry>
          <ConfigProvider theme={{
            token: {
              fontFamily: 'var(--font-noto-devnagari)',
            },
            components: {
              Button: {
                colorPrimary: 'var(--jv-red)',
                colorPrimaryHover: 'rgba(184, 40, 46, 0.8)',
                fontWeight: 700
              }
            }
          }}>
            {children}
          </ConfigProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
